apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: java-springboot-vkupsiay 
  description: Secure Supply Chain Example for Spring Boot® using Maven sample HTTP/REST application based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used tssc-gitops as the grouping
    argocd/app-selector: tssc/gitops=java-springboot-vkupsiay
    backstage.io/kubernetes-id: java-springboot-vkupsiay 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: xjiangorg/java-springboot-vkupsiay
    quay.io/repository-slug: quay_xjiang/java-springboot-vkupsiay
  tags: ["java", "spring", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 